### ISSUE TITLE
Hangs on CTRL+C, can't kill

### ISSUE THREAD

**Issue by iddm** [MegaLoler/lispcord#25]
When `depipe` was merged, the `sbcl` interpreter can't be killed via `ctrl-c/ctrl-d`. The latest output is:

```
Cache-hit: 229285649721589760   :: CHANNEL
Cache-hit: 246986189410795521   :: CHANNEL
[Event] TYPING_START
[Payload] #<HASH-TABLE :TEST EQUAL :COUNT 4 {10062AA463}>
[Event] MESSAGE_CREATE
[Payload] #<HASH-TABLE :TEST EQUAL :COUNT 4 {10062AC113}>
Cache-hit: 183254040266670080   :: USER

debugger invoked on a TYPE-ERROR in thread
#<THREAD "websocket client read thread" RUNNING {1008B275C3}>:
  The value #<LISPCORD.CLASSES:MESSAGE {10070AB223}>
  is not of type
    (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL CHARACTER).
^C
debugger invoked on a SB-SYS:INTERACTIVE-INTERRUPT in thread
#<THREAD "main thread" RUNNING {100399C783}>:
  Interactive interrupt at #x7FFFF71C474D.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE] Return from SB-UNIX:SIGINT.
  1: [ABORT   ] Exit debugger, returning to top level.

("bogus stack frame")
0] ^C

debugger invoked on a SB-SYS:INTERACTIVE-INTERRUPT in thread
#<THREAD "main thread" RUNNING {100399C783}>:
  Interactive interrupt at #x7FFFF71C474D.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE] Return from SB-UNIX:SIGINT.
  1: [ABORT   ] Reduce debugger level (to debug level 1).
  2:            Return from SB-UNIX:SIGINT.
  3:            Exit debugger, returning to top level.

("bogus stack frame")
0[2] 
0] 
* Websocket closed with code: NIL
Reason: NIL
```

**Comment by spreadLink** [comment]
It seems you are trying to interrupt the debugger? 
This is an "issue" (rather, a design decision) by SBCL, not lispcord if true.
Principally it just doesn't allow you to shut down the debugger via an interrupt, it just enters the debugger to debug the debugger…
More interesting to me is the type error that invoked the debugger in the first place. Is that an error in lispcord or in the bot?

**Comment by spreadLink** [comment]
Oh ye also, once you are in the debugger you have to invoke [ABORT]
It is possible that, due to the debugger being invoked, the heartbeat thread desynced tho so i'd advise to invoke (lispcord:disconnect <your-bot-instance>) to clean up a possibly still running websocket or heartbeat thread.

**Comment by spreadLink** [comment]
I looked through the SBCL manual and found this:
http://www.sbcl.org/manual/#Unknown-Locations-and-Interrupts
http://www.sbcl.org/manual/#Enabling-and-Disabling-the-Debugger

This should explain what is going wrong, and why I don't want to fix it in lispcord itself, but how you can fix it in your application :+1:

**Comment by iddm** [comment]
Thanks much for the info! :)

The problem was in my code.. However, you have a typo in the "README.md" ping bot example too :)
Okay, since this is not a bug of the library, I am closing this :)

**Comment by spreadLink** [comment]
where precisely?
EDIT:
nvmd, i see it
