### ISSUE TITLE
Is there a way to get mention string?

### ISSUE THREAD

**Issue by iddm** [MegaLoler/lispcord#26]
As as user I would like to have methods for mentioning stuff like users, channels, guilds, and so on (everything what could be mentioned) so that I have a very simple API for this which simply returns string. Could we have such methods?

**Comment by spreadLink** [comment]
You mean a function á la "(mention \<user>) => \<id-string>" that can then be concatenated into a string?

**Comment by iddm** [comment]
Yes!

**Comment by spreadLink** [comment]
okay, doesn't sound too hard to do

**Comment by iddm** [comment]
Maaaaaan. I don't know whether it is LISP or just you, but the commit is fu**ng amazing. The code looks so clean and understandable, and it does exactly what is needed. I don't understand the formatting though:

![Formatting](https://i.imgur.com/GU2dsFE.png)

Could you explain me please, why the words and some lines are so far from their context? I just don't know LISP so much and its guidelines :) Also, I don't try to review your code, don't feel offence.

**Comment by spreadLink** [comment]
It's github being a wonky peace of work.
I'm using emacs default formatter which (i guess?) uses 2-space-tab to indent, while github uses idk, 4 or so spaces to indent. And for some reason it also converts 2 adjacent spaces into a ab, which pulls everything apart quite far.
I'm not sure how to fix it and too lazy to look tho :sweat: 
Edit:
on the clean code issue, it's probably just lisp using long workds xD

**Comment by spreadLink** [comment]
Kay, i managed to convince emacs to use spaces now, and reformatted all the files.
The code should be easier to read now and more coherent in its indentation :+1:

**Comment by iddm** [comment]
@spreadLink You are awesome.
