### ISSUE TITLE
Is this repo maintained?

### ISSUE THREAD

**Issue by naryl** [MegaLoler/lispcord#39]
@spreadLink @MegaLoler Hello. I need Lispcord for a project and I may need to make a few patches. Do you still accept them (I see a PR by jgkamat just left without a comment for more than two months)?

Otherwise, with your approval, I can start calling my fork the main one and publish it to Quicklisp too.

**Comment by spreadLink** [comment]
Hey,
I really wanted to rework this project (especially with all of the new discord API changes) but i kept putting it off in favour of other things :/
Principally this repo is maintained (or, at least monitored), but since the project is structured around an org it's also possible to add you to it so you can work on the lib directly (which maybe is less confusing than taking over by fork).
Bonus, if i ever get the inclination i can help on this again, and you can easily message me for questions about parts of the code :)
However, you are of course free to simply fork it if you want.

**Comment by spreadLink** [comment]
Oh yeah, as for the pull request, i looked into the issue a few times but i don't understand how a function from an external library would directly depend or set fields of a structure in this lib, and i never figured out the exact issue and then...
kinda forgot 😓

**Comment by naryl** [comment]
Ok, you can give me write permissions. I'll try to implement whatever new missing features I need without touching anything else.
The only controversial feature is this one: https://github.com/naryl/lispcord/commit/7fe9fb07f40cc0fd42e2493a69fa48f8c7f4bebf#diff-09cc12f2a3e17d16a222664137bd99fdR6
Which allows introducing the bot as a user account (simply omitting "Bot" from the auth string). I don't actually intend to use it to implement selfbots but someone else may. So, it may be a better option to monkey-patch it from my project's code instead.
https://github.com/naryl/dithcord/

**Comment by spreadLink** [comment]
Hi,i already send you an invite (i hope?) for the org :)
And no need to just add missing features, i'm glad someone wants to help maintain it.

As for the selfbot thing, i'm somewhat impartial to it generally but afaik allowing them causes issues with discord support, and also somewhat cripples the libraries chances to ever be  listed on the API server, which i think would be a good goal to have.
Thankfully, as you said, it's not too difficult to just change it project-specifically, so i'd prefer that route personally.

**Comment by naryl** [comment]
I don't see it anywhere on Github but that may be just another case of poor UI design. :D
UPD: Found it on the org's page...

**Comment by naryl** [comment]
@spreadLink I've checked and discord.py actually is in both the official list here:
https://discordapp.com/developers/docs/topics/community-resources#libraries-discord-libraries

And has the user account authentication feature:
https://github.com/Rapptz/discord.py/blob/e91675291e5b5a4697f869a7a01c96aa5fa3ffea/discord/client.py#L568
https://github.com/Rapptz/discord.py/blob/e91675291e5b5a4697f869a7a01c96aa5fa3ffea/discord/http.py#L127

I guess it's ok as long as you avoid words like "selfbot" :D I'll do it exactly as discord.py does it. I.e.
```lisp
(make-bot *token* :bot nil)
```

I guess that's why the class is called `Client` instead of `Bot` in discord.py
