### ISSUE TITLE
Make it possible to auth as a user account

### ISSUE THREAD

**Issue by naryl** [MegaLoler/lispcord#41]
I've checked discord.py and it actually is both in the official list here:
https://discordapp.com/developers/docs/topics/community-resources#libraries-discord-libraries

And has the user account authentication feature:
https://github.com/Rapptz/discord.py/blob/e91675291e5b5a4697f869a7a01c96aa5fa3ffea/discord/client.py#L568
https://github.com/Rapptz/discord.py/blob/e91675291e5b5a4697f869a7a01c96aa5fa3ffea/discord/http.py#L127

I guess it's ok as long as you avoid words like "selfbot" :D I can do it exactly as discord.py does it. I.e.

```lisp
(make-bot *token* :bot nil)
```
Then it would probably make sense to rename `bot` to `client` as in discord.py too. So:

```lisp
;; Default usage
(make-client *token*)
;; User account usage
(make-client *token* :bot nil)
```

**Comment by spreadLink** [comment]
I don't really see the point of hardcoding this into the lib, but it's also such a little thing that i'm mostly ambivalent to it.
