### ISSUE TITLE
Make lispcord async?

### ISSUE THREAD

**Issue by naryl** [MegaLoler/lispcord#42]
There are several uses.
1. Make it possible for a handler to wait for another gateway event.
2. Make Discord HTTP API requests asynchronously to improve responsiveness a bit.
3. Make it possible for user code to do any long non-lispcord operation without blocking the bot.

I propose to do it in one of the two ways:
1. Using https://github.com/orthecreedence/cl-async, https://github.com/orthecreedence/blackbird, and https://github.com/orthecreedence/drakma-async. They are very fast but rely on a c library and make the code a bit like node.js's. I.e. Waiting on a future with lambdas for handling success and error.
2. Using a thread pool with OS threads which may hurt performance but will provide a lispy API and not depend on C libraries.

Of course either way will increase the complexity considerably so it may be better to leave it as is. It will be a lot easier to do it in Dithcord since it wraps Lispcord's handlers feature completely. This way Lispcord remains basically a Gateway and HTTP API wrapper with little else. I'm good either way, so @spreadLink decide if you want it specifically for Lispcord.

**Comment by spreadLink** [comment]
IIRC lispcord is already async by virtue of allowing multiple concurrent bot instances.
I have never tried it, but it should be possible to instantiate two bots with the same log-in credentials, thus allowing the user to choose which kind of async workflow they want.
But again, i've never tried it in practice, so it might be finicky.

**Comment by naryl** [comment]
It should work with Discord. I'll check if it works on Lispcord side and close this issue if it does.

**Comment by naryl** [comment]
Seems to work fine. Both bots just get exactly the same events. So, it's mostly a non-issue for Lispcord.
