### ISSUE TITLE
[bug] lispcord using 100% of the cpu while idle in slime sbcl

### ISSUE THREAD

**Issue by Inc0n** [MegaLoler/lispcord#48]
Mostly as the title suggest

Additional info: 
host machine running linux

**Comment by MistressRemilia** [comment]
Just in case it's helpful...

I hacked together a simple bot to test something yesterday and left it running overnight.  Today I came back to my laptop and noticed the same, where all four of my cores were at 95-100%, with SBCL (2.0.7 on Slackware Linux fwiw) being the reason for it all.  However the bot was idle and in a test guild that only has me and the bot.

One thing I noticed is that in my Slime window, I received the "on ready" event multiple times throughout the night.  This is something that doesn't happen with another Discord bot I wrote in another language.  Running (bt:all-theads) listed multiple websocket driver threads, at least the same number as "on ready" events I received.

I haven't investigated further yet, however.

**Comment by Inc0n** [comment]
Hmm, yh in the title I put idle as well, which is when the bot has been left idle, and I don't think I left my bot idle for long. It could have been somewhere near half an hour maybe, it has been a while now. That's when I noticed my CPU is 100%, because my fan just starts spinning like crazy.

**Comment by travv0** [comment]
I'm not sure why this was closed but when I was playing around with lispcord I ran into this as well. Might be worth reopening?

**Comment by spreadLink** [comment]
I'm not opposed to opening it again, but it's not an issue with the library itself, rather with WSD having the tendency to just keep opening OS threads

As long as WSD is locked in as a dependency (which I have to until me/someone writes another spec compliant websocket library) this is somewhat difficult to fix from my side.  After all, i can't just randomly nuke random threads, as it may be one that is currently communicating with the servers, and i don't know how to exactly discriminate between stale and actually useful threads.

**Comment by nyx-land** [comment]
FYI if anyone still is maintaining or using lispcord, I have a PR open with WSD that seems to fix the issue: https://github.com/fukamachi/websocket-driver/pull/63

**Comment by no-defun-allowed** [comment]
Running Lispcord for about 150 days now, it appears that the reader thread spins when the connection drops out in <https://github.com/fukamachi/websocket-driver/blob/master/src/ws/base.lisp#L209-L213>. Can't tell why there would be an "I/O timeout error" honestly; there doesn't seem to be any code which sets up timeouts. I modified that code to give up after 10 errors are signalled, which avoids death-spiralling but is a total hack. Then there's a race when two threads both try to close the SSL connection concurrently, which frequently enough causes a double-free and my Lisp process to die, so there needs to be a lock protecting closing the connection too.

**Comment by spreadLink** [comment]
I assume you mean the lock is supposed to be somewhere in WSD itself, but would it make sense to, for the time, stuff a lock into the lispcord client and pray for the best?

**Comment by no-defun-allowed** [comment]
It should be in WSD, as its own threads close a connection without synchronisation; I don't see where to put it in Lispcord.
