### ISSUE TITLE
[question] snowflake

### ISSUE THREAD

**Issue by Inc0n** [MegaLoler/lispcord#49]
Only after browsing utill.lisp
i ve found out that snowflake has the following type declaration:
```
(deftype snowflake () '(unsigned-byte 64))
```

Is there any particular reason to name it so, I would rather suggest to use something similar to `u64` maybe more intuitive

**Comment by spreadLink** [comment]
Yes, snowflakes are unique IDs discord assigns to objects. Discord sends them as strings, and lispcord used to just use the strings, but since most objects are interned into tables using that ID, i decided to convert them to a numeric type.
