### ISSUE TITLE
Many type errors

### ISSUE THREAD

**Issue by s-clerc** [MegaLoler/lispcord#54]
Hi I just tried to use lispcord (the example) and I'm experiencing a lot of type errors.

Immediately when the client tries to connect:
> The value `#()`, derived from the `initarg :ROLES`, can not be used to set the value of the slot `LISPCORD.CLASSES:ROLES` in `#<LISPCORD.CLASSES:EMOJI #x3021ACC5EB1D>`, because it is not of type `(VECTOR (UNSIGNED-BYTE 64))`.

when a message is sent on the server
> The value `"755133063729512448"`, derived from the `initarg :NONCE`, can not be used to set the value of the slot `LISPCORD.CLASSES:NONCE` in `#<LISPCORD.CLASSES:MESSAGE #x302003AD53CD>`, because it is not of type `(OR NULL (UNSIGNED-BYTE 64))`.

I'm not sure what I'm doing wrong, to be honest. I was worried it might be because I was using the QL version, but I'm experiencing the same issue with the downloaded version.

**Comment by spreadLink** [comment]
Hi, especially the first error seems weird. What implementation are you using? I don't recognize those type errors.

**Comment by spreadLink** [comment]
I've just looked at the docs, and it seems that at some point discord introduced the option of sending a nonce as a string. This error should be fixed now (It'd be nice if you could verify that), but the first error still eludes me.  
How can an empty vector not be of type vector?

**Comment by s-clerc** [comment]
[Fixed via external discussion]
