### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [MegaLoler/lispcord#56]
Building with SBCL 2.3.1.122-1455d60f6 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 448190cc503a0d7e59bdc0ffddb2e9dba0a706af

*example-bot* fails to build because of a failure in  _lispcord_.

*lispcord* fails to build with the following error:

```
; caught ERROR:
;   READ error during COMPILE-FILE: Package V does not exist. Line: 70, Column: 27, File-Position: 1770 Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/quicklisp/quicklisp-controller/dist/build-cache/lispcord/0f666cbb07e74cb35c5666bd504ff4919694230f/lispcord-20230417-git/src/util.lisp" {101264A863}>
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001728003}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "lispcord" "src" "util">

```

[Full log here](http://report.quicklisp.org/2023-04-17/failure-report/lispcord.html)

**Comment by spreadLink** [comment]
Should be fixed by [0beebf9](https://github.com/lispcord/lispcord/commit/0beebf9476cac01625f877907e1e627f7ed79077)

VERBOSE removed a global nickname we relied on so i had to manually add that nickname back to the packages where it was used.

**Comment by xach** [comment]
There are still problems - see https://github.com/lispcord/lispcord/blob/master/src/util.lisp#L70

**Comment by spreadLink** [comment]
Good catch, sorry I missed that. Also found two more packages that needed renaming in /classes, god knows why I decided to spread those definitions out all over the place.

**Comment by sierpinskiii** [comment]
Same issue in SBCL 2.3.0.
