### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [MegaLoler/lispcord#57]
Building with SBCL 2.3.3.83-562a1a329 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 0460017dae6404bde941f8d0097b675990e0fc37

*example-bot* fails to build with the following error:

```
Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD tid=541389 "main thread" RUNNING {1001738003}>: The name "VERBOSE" does not designate any package.

```

*lispcord* fails to build with the following error:

```
Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD tid=541394 "main thread" RUNNING {1001738003}>: The name "VERBOSE" does not designate any package.

```

[Full log here](http://report.quicklisp.org/2023-06-15/failure-report/lispcord.html)

**Comment by spreadLink** [comment]
Hopefully fixed with [a5c2156](https://github.com/lispcord/lispcord/commit/a5c21569bd5ed12f87e2991be01033f89e91b033)
