### ISSUE TITLE
call bot from app

### ISSUE THREAD

**Issue by OzarSariya** [MegaLoler/lispcord#62]
sorry to be lazy and just ask this, just too burned out with my startup to look detailed in the source code

I got the example to work and like it. How do I call the bot to submit a message to a channel from within a larger app? (E.g., if someone changes their username on https://muupi.com, the code pirate queen weaving web-apps like rick-rolls in the digital ocean with her Whale Simp Wooty the Whale)

**Comment by spreadLink** [comment]
I'm unsure what exactly you are asking for. If you want to know how you can make the bot post a message to a channel without it being a reply, you can call `create` on a `lc:partial-message` (or just a string, which will automatically convert it to a message) and a channel object (and, optionally, your bot instance).
